spring.application.name=api-gateway

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=order-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/order/**

spring.cloud.gateway.server.webmvc.routes[1].id=notification-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/notification/**

spring.cloud.gateway.server.webmvc.routes[2].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/inventory/**

management.tracing.export.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans

spring.cloud.openfeign.micrometer.enabled=true